# POST http://localhost:3333/videos
# Content-Type: application/json

# {
#   "title":"Video 01",
#   "description": "Esse é o video 01",
#   "duration": 100,
# }
curl -X POST http://localhost:3333/videos \
     -H "Content-Type: application/json" \
     -d '{
           "title": "Video 1",
           "description": "Esse é o video 01",
           "duration": 100
         }'

###
curl -X GET http://localhost:3333/videos?search=node

###
curl -X GET http://localhost:3333/videos


###
curl -X PUT http://localhost:3333/videos/b52b1496-0c47-4f47-89a4-17f8df40031a \
     -H "Content-Type: application/json" \
     -d '{
           "title": "Video 02",
           "description": "Esse é o video 01",
           "duration": 100
         }'

###
curl -X DELETE http://localhost:3333/videos/b52b1496-0c47-4f47-89a4-17f8df40031a